-- STAFF-01/02: inspect before applying (run these SELECTs separately if needed).
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='users' ORDER BY ordinal_position;
-- SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.users'::regclass;
-- SELECT role, count(*) FROM public.users GROUP BY role;
-- SELECT lower(email), count(*) FROM public.users GROUP BY lower(email) HAVING count(*) > 1;
-- SELECT tc.table_name, kcu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu USING (constraint_name,table_schema) JOIN information_schema.constraint_column_usage ccu USING (constraint_name,table_schema) WHERE tc.constraint_type='FOREIGN KEY' AND ccu.table_schema='public' AND ccu.table_name='users';
-- SELECT data_type FROM information_schema.columns WHERE table_schema='public' AND table_name='staff_roles' AND column_name='id';

BEGIN;

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS staff_role_id bigint;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS invited_by bigint;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS invited_at timestamptz;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS activated_at timestamptz;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS last_login_at timestamptz;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS session_version integer NOT NULL DEFAULT 1;

DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_role_check CHECK (role IN ('manager','supervisor','staff'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_status_check CHECK (status IN ('invited','active','suspended','inactive'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_session_version_check CHECK (session_version >= 1);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_staff_role_fk FOREIGN KEY (staff_role_id) REFERENCES public.staff_roles(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.users ADD CONSTRAINT users_invited_by_fk FOREIGN KEY (invited_by) REFERENCES public.users(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_uidx ON public.users (lower(email));
CREATE INDEX IF NOT EXISTS users_status_idx ON public.users(status);
CREATE INDEX IF NOT EXISTS users_role_idx ON public.users(role);
CREATE INDEX IF NOT EXISTS users_staff_role_id_idx ON public.users(staff_role_id);
CREATE INDEX IF NOT EXISTS users_invited_by_idx ON public.users(invited_by);

CREATE TABLE IF NOT EXISTS public.user_account_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  purpose text NOT NULL CHECK (purpose IN ('account_activation','password_reset')),
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES public.users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS user_account_tokens_hash_uidx ON public.user_account_tokens(token_hash);
CREATE INDEX IF NOT EXISTS user_account_tokens_user_idx ON public.user_account_tokens(user_id);
CREATE INDEX IF NOT EXISTS user_account_tokens_expiry_idx ON public.user_account_tokens(expires_at);
CREATE INDEX IF NOT EXISTS user_account_tokens_purpose_idx ON public.user_account_tokens(purpose);
CREATE INDEX IF NOT EXISTS user_account_tokens_created_by_idx ON public.user_account_tokens(created_by);

CREATE TABLE IF NOT EXISTS public.staff_account_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  target_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS staff_account_audit_actor_idx ON public.staff_account_audit(actor_user_id);
CREATE INDEX IF NOT EXISTS staff_account_audit_target_idx ON public.staff_account_audit(target_user_id);
CREATE INDEX IF NOT EXISTS staff_account_audit_created_idx ON public.staff_account_audit(created_at DESC);

-- These public-schema tables are server-only. RLS with no Data API policies
-- prevents anon/authenticated PostgREST access; Flask uses its server DB role.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_account_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_account_audit ENABLE ROW LEVEL SECURITY;

COMMIT;
